// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package client_api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	PingMessage
	DummyDataRequest
	DummyDataResponse
*/
package client_api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingMessage struct {
	Greeting string `protobuf:"bytes,1,opt,name=greeting" json:"greeting,omitempty"`
}

func (m *PingMessage) Reset()                    { *m = PingMessage{} }
func (m *PingMessage) String() string            { return proto.CompactTextString(m) }
func (*PingMessage) ProtoMessage()               {}
func (*PingMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PingMessage) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type DummyDataRequest struct {
	Keyname string `protobuf:"bytes,1,opt,name=keyname" json:"keyname,omitempty"`
}

func (m *DummyDataRequest) Reset()                    { *m = DummyDataRequest{} }
func (m *DummyDataRequest) String() string            { return proto.CompactTextString(m) }
func (*DummyDataRequest) ProtoMessage()               {}
func (*DummyDataRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DummyDataRequest) GetKeyname() string {
	if m != nil {
		return m.Keyname
	}
	return ""
}

type DummyDataResponse struct {
	Id        int64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Firstname string  `protobuf:"bytes,2,opt,name=firstname" json:"firstname,omitempty"`
	Balance   float64 `protobuf:"fixed64,3,opt,name=balance" json:"balance,omitempty"`
}

func (m *DummyDataResponse) Reset()                    { *m = DummyDataResponse{} }
func (m *DummyDataResponse) String() string            { return proto.CompactTextString(m) }
func (*DummyDataResponse) ProtoMessage()               {}
func (*DummyDataResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DummyDataResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DummyDataResponse) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *DummyDataResponse) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func init() {
	proto.RegisterType((*PingMessage)(nil), "client_api.PingMessage")
	proto.RegisterType((*DummyDataRequest)(nil), "client_api.DummyDataRequest")
	proto.RegisterType((*DummyDataResponse)(nil), "client_api.DummyDataResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Ping service

type PingClient interface {
	SayHello(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*PingMessage, error)
	GetDummyData(ctx context.Context, in *DummyDataRequest, opts ...grpc.CallOption) (*DummyDataResponse, error)
}

type pingClient struct {
	cc *grpc.ClientConn
}

func NewPingClient(cc *grpc.ClientConn) PingClient {
	return &pingClient{cc}
}

func (c *pingClient) SayHello(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*PingMessage, error) {
	out := new(PingMessage)
	err := grpc.Invoke(ctx, "/client_api.Ping/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingClient) GetDummyData(ctx context.Context, in *DummyDataRequest, opts ...grpc.CallOption) (*DummyDataResponse, error) {
	out := new(DummyDataResponse)
	err := grpc.Invoke(ctx, "/client_api.Ping/GetDummyData", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Ping service

type PingServer interface {
	SayHello(context.Context, *PingMessage) (*PingMessage, error)
	GetDummyData(context.Context, *DummyDataRequest) (*DummyDataResponse, error)
}

func RegisterPingServer(s *grpc.Server, srv PingServer) {
	s.RegisterService(&_Ping_serviceDesc, srv)
}

func _Ping_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client_api.Ping/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).SayHello(ctx, req.(*PingMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ping_GetDummyData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DummyDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).GetDummyData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client_api.Ping/GetDummyData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).GetDummyData(ctx, req.(*DummyDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ping_serviceDesc = grpc.ServiceDesc{
	ServiceName: "client_api.Ping",
	HandlerType: (*PingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Ping_SayHello_Handler,
		},
		{
			MethodName: "GetDummyData",
			Handler:    _Ping_GetDummyData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x86, 0x99, 0xf4, 0xe3, 0x6b, 0x73, 0xac, 0x7f, 0x03, 0x62, 0x08, 0x11, 0xca, 0xac, 0xaa,
	0x48, 0x82, 0xba, 0x73, 0x5d, 0xd0, 0x8d, 0x50, 0xe2, 0xd2, 0x85, 0x9c, 0xb4, 0xc7, 0x61, 0x30,
	0x99, 0x19, 0x33, 0xd3, 0x45, 0xb6, 0xde, 0x82, 0xb7, 0xe3, 0x5d, 0x78, 0x0b, 0x5e, 0x88, 0x34,
	0xb5, 0x6d, 0x10, 0xba, 0x7c, 0xe7, 0xbc, 0xf3, 0xcc, 0x79, 0x06, 0x42, 0xb4, 0x2a, 0xb5, 0xb5,
	0xf1, 0x86, 0xc3, 0xac, 0x54, 0xa4, 0xfd, 0x33, 0x5a, 0x15, 0x27, 0xd2, 0x18, 0x59, 0x52, 0x86,
	0x56, 0x65, 0xa8, 0xb5, 0xf1, 0xe8, 0x95, 0xd1, 0x6e, 0xd5, 0x14, 0xe7, 0xb0, 0x37, 0x55, 0x5a,
	0x3e, 0x90, 0x73, 0x28, 0x89, 0xc7, 0x30, 0x90, 0x35, 0x91, 0x57, 0x5a, 0x46, 0x6c, 0xc4, 0xc6,
	0x61, 0xbe, 0xc9, 0xe2, 0x12, 0x8e, 0x26, 0x8b, 0xaa, 0x6a, 0x26, 0xe8, 0x31, 0xa7, 0xb7, 0x05,
	0x39, 0xcf, 0x23, 0xe8, 0xbf, 0x52, 0xa3, 0xb1, 0xa2, 0xdf, 0xfa, 0x3a, 0x8a, 0x27, 0x38, 0xee,
	0xb4, 0x9d, 0x35, 0xda, 0x11, 0x3f, 0x80, 0x40, 0xcd, 0xdb, 0x66, 0x2f, 0x0f, 0xd4, 0x9c, 0x27,
	0x10, 0xbe, 0xa8, 0xda, 0xf9, 0x16, 0x10, 0xb4, 0x80, 0xed, 0xc1, 0x12, 0x5e, 0x60, 0x89, 0x7a,
	0x46, 0x51, 0x6f, 0xc4, 0xc6, 0x2c, 0x5f, 0xc7, 0xeb, 0x4f, 0x06, 0xff, 0x96, 0x6b, 0xf3, 0x29,
	0x0c, 0x1e, 0xb1, 0xb9, 0xa7, 0xb2, 0x34, 0xfc, 0x34, 0xdd, 0x5a, 0xa7, 0x1d, 0xa9, 0x78, 0xd7,
	0x40, 0xf0, 0xf7, 0xaf, 0xef, 0x8f, 0x60, 0x28, 0xfa, 0xd9, 0x55, 0x66, 0x95, 0x96, 0xb7, 0xec,
	0x82, 0x17, 0x30, 0xbc, 0x23, 0xbf, 0x59, 0x9d, 0x27, 0xdd, 0xcb, 0x7f, 0xfd, 0xe3, 0xb3, 0x1d,
	0xd3, 0x95, 0xaf, 0x38, 0x69, 0x1f, 0x38, 0xe4, 0xfb, 0x99, 0xec, 0x30, 0x8b, 0xff, 0xed, 0xdf,
	0xdf, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0x20, 0x87, 0x5e, 0x77, 0xb2, 0x01, 0x00, 0x00,
}
