// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dummy_data.proto

/*
Package dummy is a generated protocol buffer package.

It is generated from these files:
	dummy_data.proto

It has these top-level messages:
	DummyData
	DummyDataBag
*/
package dummy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DummyData struct {
	ID         int64   `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	PID        int64   `protobuf:"varint,2,opt,name=PID" json:"PID,omitempty"`
	FirstName  string  `protobuf:"bytes,3,opt,name=FirstName" json:"FirstName,omitempty"`
	LastName   string  `protobuf:"bytes,4,opt,name=LastName" json:"LastName,omitempty"`
	Balance    float64 `protobuf:"fixed64,5,opt,name=Balance" json:"Balance,omitempty"`
	MaxCredit  float64 `protobuf:"fixed64,6,opt,name=MaxCredit" json:"MaxCredit,omitempty"`
	MaxDebit   float64 `protobuf:"fixed64,7,opt,name=MaxDebit" json:"MaxDebit,omitempty"`
	Score      float64 `protobuf:"fixed64,8,opt,name=Score" json:"Score,omitempty"`
	IsActive   bool    `protobuf:"varint,9,opt,name=IsActive" json:"IsActive,omitempty"`
	Created_At int64   `protobuf:"varint,10,opt,name=Created_At,json=CreatedAt" json:"Created_At,omitempty"`
}

func (m *DummyData) Reset()                    { *m = DummyData{} }
func (m *DummyData) String() string            { return proto.CompactTextString(m) }
func (*DummyData) ProtoMessage()               {}
func (*DummyData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DummyData) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *DummyData) GetPID() int64 {
	if m != nil {
		return m.PID
	}
	return 0
}

func (m *DummyData) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *DummyData) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *DummyData) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *DummyData) GetMaxCredit() float64 {
	if m != nil {
		return m.MaxCredit
	}
	return 0
}

func (m *DummyData) GetMaxDebit() float64 {
	if m != nil {
		return m.MaxDebit
	}
	return 0
}

func (m *DummyData) GetScore() float64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *DummyData) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *DummyData) GetCreated_At() int64 {
	if m != nil {
		return m.Created_At
	}
	return 0
}

type DummyDataBag struct {
	Bag []*DummyData `protobuf:"bytes,1,rep,name=Bag" json:"Bag,omitempty"`
}

func (m *DummyDataBag) Reset()                    { *m = DummyDataBag{} }
func (m *DummyDataBag) String() string            { return proto.CompactTextString(m) }
func (*DummyDataBag) ProtoMessage()               {}
func (*DummyDataBag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DummyDataBag) GetBag() []*DummyData {
	if m != nil {
		return m.Bag
	}
	return nil
}

func init() {
	proto.RegisterType((*DummyData)(nil), "dummy.DummyData")
	proto.RegisterType((*DummyDataBag)(nil), "dummy.DummyDataBag")
}

func init() { proto.RegisterFile("dummy_data.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xd9, 0xc4, 0xb4, 0xc9, 0x28, 0x12, 0x16, 0x0f, 0x83, 0x28, 0x84, 0x9c, 0x72, 0xca,
	0xa1, 0x3e, 0x41, 0xd2, 0x45, 0x08, 0x58, 0x91, 0xf5, 0x01, 0xca, 0x34, 0x59, 0x4a, 0xc0, 0x18,
	0xd9, 0x8e, 0x52, 0xdf, 0xc1, 0x87, 0x96, 0x5d, 0xeb, 0xf6, 0x36, 0xff, 0xf7, 0xed, 0x0e, 0xcc,
	0x0f, 0xf9, 0xf0, 0x39, 0x4d, 0xdf, 0xdb, 0x81, 0x98, 0xea, 0x0f, 0x3b, 0xf3, 0x2c, 0x13, 0x4f,
	0xca, 0x9f, 0x08, 0x32, 0xe5, 0x26, 0x45, 0x4c, 0xf2, 0x1a, 0xa2, 0x4e, 0xa1, 0x28, 0x44, 0x15,
	0xeb, 0xa8, 0x53, 0x32, 0x87, 0xf8, 0xa5, 0x53, 0x18, 0x79, 0xe0, 0x46, 0x79, 0x07, 0xd9, 0xe3,
	0x68, 0x0f, 0xfc, 0x4c, 0x93, 0xc1, 0xb8, 0x10, 0x55, 0xa6, 0xcf, 0x40, 0xde, 0x42, 0xfa, 0x44,
	0x27, 0x79, 0xe1, 0x65, 0xc8, 0x12, 0x61, 0xd9, 0xd2, 0x1b, 0xbd, 0xf7, 0x06, 0x93, 0x42, 0x54,
	0x42, 0xff, 0x47, 0xb7, 0x73, 0x43, 0xc7, 0xb5, 0x35, 0xc3, 0xc8, 0xb8, 0xf0, 0xee, 0x0c, 0xdc,
	0xce, 0x0d, 0x1d, 0x95, 0xd9, 0x8d, 0x8c, 0x4b, 0x2f, 0x43, 0x96, 0x37, 0x90, 0xbc, 0xf6, 0xb3,
	0x35, 0x98, 0x7a, 0xf1, 0x17, 0xdc, 0x8f, 0xee, 0xd0, 0xf4, 0x3c, 0x7e, 0x19, 0xcc, 0x0a, 0x51,
	0xa5, 0x3a, 0x64, 0x79, 0x0f, 0xb0, 0xb6, 0x86, 0xd8, 0x0c, 0xdb, 0x86, 0x11, 0xfc, 0x61, 0xd9,
	0x89, 0x34, 0x5c, 0xae, 0xe0, 0x2a, 0xb4, 0xd1, 0xd2, 0x5e, 0x96, 0x10, 0xb7, 0xb4, 0x47, 0x51,
	0xc4, 0xd5, 0xe5, 0x2a, 0xaf, 0x7d, 0x67, 0x75, 0x78, 0xa1, 0x9d, 0xdc, 0x2d, 0x7c, 0xa1, 0x0f,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x00, 0x5b, 0xb6, 0x81, 0x64, 0x01, 0x00, 0x00,
}
