// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	PingMessage
	AnnouncedVersionRequest
	AnnouncedVersionResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingMessage struct {
	Greeting string `protobuf:"bytes,1,opt,name=greeting" json:"greeting,omitempty"`
}

func (m *PingMessage) Reset()                    { *m = PingMessage{} }
func (m *PingMessage) String() string            { return proto.CompactTextString(m) }
func (*PingMessage) ProtoMessage()               {}
func (*PingMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PingMessage) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type AnnouncedVersionRequest struct {
	Namespace string `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	Entity    string `protobuf:"bytes,2,opt,name=entity" json:"entity,omitempty"`
}

func (m *AnnouncedVersionRequest) Reset()                    { *m = AnnouncedVersionRequest{} }
func (m *AnnouncedVersionRequest) String() string            { return proto.CompactTextString(m) }
func (*AnnouncedVersionRequest) ProtoMessage()               {}
func (*AnnouncedVersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AnnouncedVersionRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *AnnouncedVersionRequest) GetEntity() string {
	if m != nil {
		return m.Entity
	}
	return ""
}

type AnnouncedVersionResponse struct {
	Currentversion string `protobuf:"bytes,1,opt,name=currentversion" json:"currentversion,omitempty"`
}

func (m *AnnouncedVersionResponse) Reset()                    { *m = AnnouncedVersionResponse{} }
func (m *AnnouncedVersionResponse) String() string            { return proto.CompactTextString(m) }
func (*AnnouncedVersionResponse) ProtoMessage()               {}
func (*AnnouncedVersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AnnouncedVersionResponse) GetCurrentversion() string {
	if m != nil {
		return m.Currentversion
	}
	return ""
}

func init() {
	proto.RegisterType((*PingMessage)(nil), "api.PingMessage")
	proto.RegisterType((*AnnouncedVersionRequest)(nil), "api.AnnouncedVersionRequest")
	proto.RegisterType((*AnnouncedVersionResponse)(nil), "api.AnnouncedVersionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Ping service

type PingClient interface {
	SayHello(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*PingMessage, error)
	GetAnnouncedVersion(ctx context.Context, in *AnnouncedVersionRequest, opts ...grpc.CallOption) (*AnnouncedVersionResponse, error)
}

type pingClient struct {
	cc *grpc.ClientConn
}

func NewPingClient(cc *grpc.ClientConn) PingClient {
	return &pingClient{cc}
}

func (c *pingClient) SayHello(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*PingMessage, error) {
	out := new(PingMessage)
	err := grpc.Invoke(ctx, "/api.Ping/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingClient) GetAnnouncedVersion(ctx context.Context, in *AnnouncedVersionRequest, opts ...grpc.CallOption) (*AnnouncedVersionResponse, error) {
	out := new(AnnouncedVersionResponse)
	err := grpc.Invoke(ctx, "/api.Ping/GetAnnouncedVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Ping service

type PingServer interface {
	SayHello(context.Context, *PingMessage) (*PingMessage, error)
	GetAnnouncedVersion(context.Context, *AnnouncedVersionRequest) (*AnnouncedVersionResponse, error)
}

func RegisterPingServer(s *grpc.Server, srv PingServer) {
	s.RegisterService(&_Ping_serviceDesc, srv)
}

func _Ping_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Ping/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).SayHello(ctx, req.(*PingMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ping_GetAnnouncedVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnnouncedVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).GetAnnouncedVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Ping/GetAnnouncedVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).GetAnnouncedVersion(ctx, req.(*AnnouncedVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ping_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Ping",
	HandlerType: (*PingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Ping_SayHello_Handler,
		},
		{
			MethodName: "GetAnnouncedVersion",
			Handler:    _Ping_GetAnnouncedVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0x95, 0xda, 0x8c, 0x22, 0x32, 0x4a, 0x0d, 0x21, 0x82, 0xec, 0x41, 0xd4, 0x43,
	0x83, 0x7a, 0xf3, 0x66, 0x2f, 0x7a, 0x11, 0xa5, 0x82, 0xf7, 0x35, 0x0e, 0xcb, 0x42, 0x9c, 0x59,
	0xb3, 0x1b, 0xa1, 0x57, 0x5f, 0xc1, 0xd7, 0xf1, 0x2d, 0x7c, 0x05, 0x1f, 0x44, 0x9a, 0x04, 0x95,
	0x86, 0x1e, 0xe7, 0xff, 0xf7, 0xff, 0x77, 0xbf, 0x1d, 0x88, 0xb5, 0xb3, 0x13, 0x57, 0x49, 0x10,
	0x5c, 0xd3, 0xce, 0xa6, 0x99, 0x11, 0x31, 0x25, 0xe5, 0xda, 0xd9, 0x5c, 0x33, 0x4b, 0xd0, 0xc1,
	0x0a, 0xfb, 0xf6, 0x88, 0x3a, 0x81, 0xcd, 0x7b, 0xcb, 0xe6, 0x96, 0xbc, 0xd7, 0x86, 0x30, 0x85,
	0x91, 0xa9, 0x88, 0x82, 0x65, 0x93, 0x44, 0x87, 0xd1, 0x71, 0x3c, 0xfb, 0x9d, 0xd5, 0x1d, 0xec,
	0x5f, 0x31, 0x4b, 0xcd, 0x05, 0x3d, 0x3f, 0x52, 0xe5, 0xad, 0xf0, 0x8c, 0x5e, 0x6b, 0xf2, 0x01,
	0x33, 0x88, 0x59, 0xbf, 0x90, 0x77, 0xba, 0xa0, 0x2e, 0xf7, 0x27, 0xe0, 0x18, 0x86, 0xc4, 0xc1,
	0x86, 0x79, 0x32, 0x68, 0xac, 0x6e, 0x52, 0x53, 0x48, 0xfa, 0x85, 0xde, 0x09, 0x7b, 0xc2, 0x23,
	0xd8, 0x2e, 0xea, 0xaa, 0x22, 0x0e, 0x6f, 0xad, 0xd3, 0xd5, 0x2e, 0xa9, 0xe7, 0x9f, 0x11, 0xac,
	0x2f, 0x00, 0x70, 0x0a, 0xa3, 0x07, 0x3d, 0xbf, 0xa1, 0xb2, 0x14, 0xdc, 0x99, 0x2c, 0xfe, 0xe0,
	0x1f, 0x57, 0xda, 0x53, 0x14, 0xbe, 0x7f, 0x7d, 0x7f, 0x0c, 0xb6, 0xd4, 0x46, 0x7e, 0x96, 0x3b,
	0xcb, 0xe6, 0x32, 0x3a, 0x45, 0x07, 0xbb, 0xd7, 0x14, 0x96, 0xdf, 0x84, 0x59, 0x13, 0x5e, 0xc1,
	0x9e, 0x1e, 0xac, 0x70, 0x5b, 0x10, 0x95, 0x35, 0xf7, 0x8c, 0x71, 0x2f, 0x37, 0xfd, 0xea, 0xa7,
	0x61, 0xb3, 0x85, 0x8b, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x2f, 0x11, 0xd8, 0xb5, 0x01,
	0x00, 0x00,
}
